name: TEST CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [dev-temp]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
        env:
          REACT_APP_API_DEV: ${{ secrets.REACT_APP_API_DEV }}
      - run: yarn install
      - run: yarn build
